export const subList = [
  { name: 'Accounting', slug: 'accounting' },
  {
    name: 'Entrepreneurship',
    slug: 'entrepreneurship',
  },
  { name: 'Gigs & Side Projects', slug: 'gigs-side-projects' },
  { name: 'Investing', slug: 'investing' },
  { name: 'Management & Leadership', slug: 'management-leadership' },
  {
    name: 'Marketing & Sales',
    slug: 'marketing-sales',
  },
  { name: 'Networking, Careers & Jobs', slug: 'networking-careers-jobs' },
  { name: 'Personal Finance', slug: 'personal-finance' },
  { name: 'Real Estate', slug: 'real-estate' },
  { name: 'Web Development', slug: 'web-development' },
  { name: 'Mobile Development', slug: 'mobile-development' },
  { name: 'Game Development', slug: 'game-development' },
  { name: 'Programming Languages', slug: 'programming-languages' },
  { name: 'DevOps', slug: 'devops' },
  { name: 'Fiction', slug: 'fiction' },
  { name: 'Non-Fiction', slug: 'non-fiction' },
  { name: 'Blogging', slug: 'blogging' },
  { name: 'Copywriting', slug: 'copywriting' },
  { name: 'Self-Publishing', slug: 'self-publishing' },
  { name: 'Online Courses', slug: 'online-courses' },
  { name: 'Tutoring', slug: 'tutoring' },
  { name: 'Test Preparation', slug: 'test-preparation' },
  { name: 'Language Learning', slug: 'language-learning' },
  { name: 'Productivity', slug: 'productivity' },
  { name: 'Personal Development', slug: 'personal-development' },
  { name: 'Mindfulness', slug: 'mindfulness' },
  { name: 'Career Growth', slug: 'career-growth' },
  { name: 'Workout Plans', slug: 'workout-plans' },
  { name: 'Nutrition', slug: 'nutrition' },
  { name: 'Mental Health', slug: 'mental-health' },
  { name: 'Yoga', slug: 'yoga' },
  { name: 'UI/UX', slug: 'ui-ux' },
  { name: 'Graphic Design', slug: 'graphic-design' },
  { name: '3D Modeling', slug: '3d-modeling' },
  { name: 'Typography', slug: 'typography' },
  { name: 'Watercolor', slug: 'watercolor' },
  { name: 'Acrylic', slug: 'acrylic' },
  { name: 'Oil', slug: 'oil' },
  { name: 'Pastel', slug: 'pastel' },
  { name: 'Charcoal', slug: 'charcoal' },
  { name: 'Songwriting', slug: 'songwriting' },
  { name: 'Music Production', slug: 'music-production' },
  { name: 'Music Theory', slug: 'music-theory' },
  { name: 'Music History', slug: 'music-history' },
  { name: 'Portrait', slug: 'portrait' },
  { name: 'Landscape', slug: 'landscape' },
  { name: 'Street Photography', slug: 'street-photography' },
  { name: 'Nature', slug: 'nature' },
  { name: 'Macro', slug: 'macro' },
];
